// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: odds.proto

package oddspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ── Request ────────────────────────────────────
type EquityRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The calling hand's ID (for tracing / logging)
	HandId string `protobuf:"bytes,1,opt,name=hand_id,json=handId,proto3" json:"hand_id,omitempty"`
	// "FLOP" | "TURN" | "RIVER"
	Street string `protobuf:"bytes,2,opt,name=street,proto3" json:"street,omitempty"`
	// Each player still in the hand
	Players []*PlayerHand `protobuf:"bytes,3,rep,name=players,proto3" json:"players,omitempty"`
	// Community cards dealt so far (3 on flop, 4 on turn, 5 on river)
	BoardCards []string `protobuf:"bytes,4,rep,name=board_cards,json=boardCards,proto3" json:"board_cards,omitempty"`
	// If true, enumerate all remaining combos exactly; else run Monte Carlo
	Exact bool `protobuf:"varint,5,opt,name=exact,proto3" json:"exact,omitempty"`
	// Monte Carlo trials (ignored when exact=true); 0 → server default (50 000)
	Trials        int32 `protobuf:"varint,6,opt,name=trials,proto3" json:"trials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquityRequest) Reset() {
	*x = EquityRequest{}
	mi := &file_odds_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquityRequest) ProtoMessage() {}

func (x *EquityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_odds_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquityRequest.ProtoReflect.Descriptor instead.
func (*EquityRequest) Descriptor() ([]byte, []int) {
	return file_odds_proto_rawDescGZIP(), []int{0}
}

func (x *EquityRequest) GetHandId() string {
	if x != nil {
		return x.HandId
	}
	return ""
}

func (x *EquityRequest) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *EquityRequest) GetPlayers() []*PlayerHand {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *EquityRequest) GetBoardCards() []string {
	if x != nil {
		return x.BoardCards
	}
	return nil
}

func (x *EquityRequest) GetExact() bool {
	if x != nil {
		return x.Exact
	}
	return false
}

func (x *EquityRequest) GetTrials() int32 {
	if x != nil {
		return x.Trials
	}
	return 0
}

type PlayerHand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Seat  int32                  `protobuf:"varint,1,opt,name=seat,proto3" json:"seat,omitempty"`
	// Exactly two hole cards, e.g. ["Ah", "Kd"]
	HoleCards     []string `protobuf:"bytes,2,rep,name=hole_cards,json=holeCards,proto3" json:"hole_cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerHand) Reset() {
	*x = PlayerHand{}
	mi := &file_odds_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerHand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerHand) ProtoMessage() {}

func (x *PlayerHand) ProtoReflect() protoreflect.Message {
	mi := &file_odds_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerHand.ProtoReflect.Descriptor instead.
func (*PlayerHand) Descriptor() ([]byte, []int) {
	return file_odds_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerHand) GetSeat() int32 {
	if x != nil {
		return x.Seat
	}
	return 0
}

func (x *PlayerHand) GetHoleCards() []string {
	if x != nil {
		return x.HoleCards
	}
	return nil
}

// ── Response ───────────────────────────────────
type EquityResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	HandId   string                 `protobuf:"bytes,1,opt,name=hand_id,json=handId,proto3" json:"hand_id,omitempty"`
	Equities []*SeatEquity          `protobuf:"bytes,2,rep,name=equities,proto3" json:"equities,omitempty"`
	// Actual trials run (same as request.trials for MC, or exact combos count)
	TrialsRun int32 `protobuf:"varint,3,opt,name=trials_run,json=trialsRun,proto3" json:"trials_run,omitempty"`
	// Computation duration in milliseconds
	DurationMs    int64 `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquityResponse) Reset() {
	*x = EquityResponse{}
	mi := &file_odds_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquityResponse) ProtoMessage() {}

func (x *EquityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_odds_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquityResponse.ProtoReflect.Descriptor instead.
func (*EquityResponse) Descriptor() ([]byte, []int) {
	return file_odds_proto_rawDescGZIP(), []int{2}
}

func (x *EquityResponse) GetHandId() string {
	if x != nil {
		return x.HandId
	}
	return ""
}

func (x *EquityResponse) GetEquities() []*SeatEquity {
	if x != nil {
		return x.Equities
	}
	return nil
}

func (x *EquityResponse) GetTrialsRun() int32 {
	if x != nil {
		return x.TrialsRun
	}
	return 0
}

func (x *EquityResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type SeatEquity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seat          int32                  `protobuf:"varint,1,opt,name=seat,proto3" json:"seat,omitempty"`
	WinPct        float64                `protobuf:"fixed64,2,opt,name=win_pct,json=winPct,proto3" json:"win_pct,omitempty"`
	TiePct        float64                `protobuf:"fixed64,3,opt,name=tie_pct,json=tiePct,proto3" json:"tie_pct,omitempty"`
	LosePct       float64                `protobuf:"fixed64,4,opt,name=lose_pct,json=losePct,proto3" json:"lose_pct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeatEquity) Reset() {
	*x = SeatEquity{}
	mi := &file_odds_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeatEquity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeatEquity) ProtoMessage() {}

func (x *SeatEquity) ProtoReflect() protoreflect.Message {
	mi := &file_odds_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeatEquity.ProtoReflect.Descriptor instead.
func (*SeatEquity) Descriptor() ([]byte, []int) {
	return file_odds_proto_rawDescGZIP(), []int{3}
}

func (x *SeatEquity) GetSeat() int32 {
	if x != nil {
		return x.Seat
	}
	return 0
}

func (x *SeatEquity) GetWinPct() float64 {
	if x != nil {
		return x.WinPct
	}
	return 0
}

func (x *SeatEquity) GetTiePct() float64 {
	if x != nil {
		return x.TiePct
	}
	return 0
}

func (x *SeatEquity) GetLosePct() float64 {
	if x != nil {
		return x.LosePct
	}
	return 0
}

// ── Ping ───────────────────────────────────────
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_odds_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_odds_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_odds_proto_rawDescGZIP(), []int{4}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "ok"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_odds_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_odds_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_odds_proto_rawDescGZIP(), []int{5}
}

func (x *PingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_odds_proto protoreflect.FileDescriptor

const file_odds_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"odds.proto\x12\n" +
	"poker.odds\"\xc1\x01\n" +
	"\rEquityRequest\x12\x17\n" +
	"\ahand_id\x18\x01 \x01(\tR\x06handId\x12\x16\n" +
	"\x06street\x18\x02 \x01(\tR\x06street\x120\n" +
	"\aplayers\x18\x03 \x03(\v2\x16.poker.odds.PlayerHandR\aplayers\x12\x1f\n" +
	"\vboard_cards\x18\x04 \x03(\tR\n" +
	"boardCards\x12\x14\n" +
	"\x05exact\x18\x05 \x01(\bR\x05exact\x12\x16\n" +
	"\x06trials\x18\x06 \x01(\x05R\x06trials\"?\n" +
	"\n" +
	"PlayerHand\x12\x12\n" +
	"\x04seat\x18\x01 \x01(\x05R\x04seat\x12\x1d\n" +
	"\n" +
	"hole_cards\x18\x02 \x03(\tR\tholeCards\"\x9d\x01\n" +
	"\x0eEquityResponse\x12\x17\n" +
	"\ahand_id\x18\x01 \x01(\tR\x06handId\x122\n" +
	"\bequities\x18\x02 \x03(\v2\x16.poker.odds.SeatEquityR\bequities\x12\x1d\n" +
	"\n" +
	"trials_run\x18\x03 \x01(\x05R\ttrialsRun\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x03R\n" +
	"durationMs\"m\n" +
	"\n" +
	"SeatEquity\x12\x12\n" +
	"\x04seat\x18\x01 \x01(\x05R\x04seat\x12\x17\n" +
	"\awin_pct\x18\x02 \x01(\x01R\x06winPct\x12\x17\n" +
	"\atie_pct\x18\x03 \x01(\x01R\x06tiePct\x12\x19\n" +
	"\blose_pct\x18\x04 \x01(\x01R\alosePct\"\r\n" +
	"\vPingRequest\"&\n" +
	"\fPingResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\x92\x01\n" +
	"\vOddsService\x12H\n" +
	"\x0fCalculateEquity\x12\x19.poker.odds.EquityRequest\x1a\x1a.poker.odds.EquityResponse\x129\n" +
	"\x04Ping\x12\x17.poker.odds.PingRequest\x1a\x18.poker.odds.PingResponseBB\n" +
	"\x0ecom.poker.grpcB\tOddsProtoZ%github.com/poker/go-odds/proto;oddspbb\x06proto3"

var (
	file_odds_proto_rawDescOnce sync.Once
	file_odds_proto_rawDescData []byte
)

func file_odds_proto_rawDescGZIP() []byte {
	file_odds_proto_rawDescOnce.Do(func() {
		file_odds_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_odds_proto_rawDesc), len(file_odds_proto_rawDesc)))
	})
	return file_odds_proto_rawDescData
}

var file_odds_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_odds_proto_goTypes = []any{
	(*EquityRequest)(nil),  // 0: poker.odds.EquityRequest
	(*PlayerHand)(nil),     // 1: poker.odds.PlayerHand
	(*EquityResponse)(nil), // 2: poker.odds.EquityResponse
	(*SeatEquity)(nil),     // 3: poker.odds.SeatEquity
	(*PingRequest)(nil),    // 4: poker.odds.PingRequest
	(*PingResponse)(nil),   // 5: poker.odds.PingResponse
}
var file_odds_proto_depIdxs = []int32{
	1, // 0: poker.odds.EquityRequest.players:type_name -> poker.odds.PlayerHand
	3, // 1: poker.odds.EquityResponse.equities:type_name -> poker.odds.SeatEquity
	0, // 2: poker.odds.OddsService.CalculateEquity:input_type -> poker.odds.EquityRequest
	4, // 3: poker.odds.OddsService.Ping:input_type -> poker.odds.PingRequest
	2, // 4: poker.odds.OddsService.CalculateEquity:output_type -> poker.odds.EquityResponse
	5, // 5: poker.odds.OddsService.Ping:output_type -> poker.odds.PingResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_odds_proto_init() }
func file_odds_proto_init() {
	if File_odds_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_odds_proto_rawDesc), len(file_odds_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_odds_proto_goTypes,
		DependencyIndexes: file_odds_proto_depIdxs,
		MessageInfos:      file_odds_proto_msgTypes,
	}.Build()
	File_odds_proto = out.File
	file_odds_proto_goTypes = nil
	file_odds_proto_depIdxs = nil
}
