global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "java-api"
    static_configs:
      - targets: ["java-api:8080"]
    metrics_path: /actuator/prometheus

  - job_name: "go-odds"
    static_configs:
      - targets: ["go-odds:9091"]
    metrics_path: /metrics
